### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by SanatLV** [mak-it/omniauth-draugiem#2]
Could not authenticate you from Draugiem because "Invalid response".
I made up a setup for new omniauth strategy. I'm using devise + omniauth tutorial from omniauth developers team.
What could be a problem?

**Comment by ebeigarts** [comment]
@SanatLV don't know, is there a stack trace or additional log messages? https://github.com/intridea/omniauth#logging

**Comment by SanatLV** [comment]
I have changed name of a directory where omniauth_callbacks_controller.rb was ( it was in app/controllers, but it works perfectly when it is in app/controllers/users directory ).
I have solved this issue.
