### ISSUE TITLE
Rest-client 1.8 not compatible with ruby >=2.4.x

### ISSUE THREAD

**Issue by OlegsBoldirevs** [mak-it/omniauth-draugiem#6]
Rest-client 1.8 not compatible with ruby >=2.4.x due to missing ciphers key in `OpenSSL::SSL::SSLContext::DEFAULT_PARAMS`

https://github.com/rest-client/rest-client/issues/612

What is the protocol to fix this?

**Comment by ebeigarts** [comment]
@OlegsBoldirevs I think we need to use rest-client 2.0+ `s.add_runtime_dependency "rest-client", "~> 2.0"`
